name: Bloomberg Harvester Matrix

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Année à aspirer'
        required: true
        default: '2014'
      month:
        description: 'Mois (1 à 12, ou tapez "ALL" pour toute l année)'
        required: true
        default: '2' # Par défaut : Février pour le test

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        part: [1, 2]
        # Si on a mis "ALL", ça fait les 12 mois, sinon seulement le mois choisi
        month: ${{ fromJson(github.event.inputs.month == 'ALL' && '[1,2,3,4,5,6,7,8,9,10,11,12]' || format('[{0}]', github.event.inputs.month)) }}

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer Playwright & Firefox
        run: |
          npm install playwright
          npx playwright install --with-deps firefox

      - name: Lancer l aspiration (${{ github.event.inputs.year }} - M${{ matrix.month }} P${{ matrix.part }})
        run: node harvest_chunk.js ${{ github.event.inputs.year }} ${{ matrix.month }} ${{ matrix.part }}

      - name: Sauvegarder les fichiers en Zip
        uses: actions/upload-artifact@v4
        with:
          name: bbg_${{ github.event.inputs.year }}_m${{ matrix.month }}_p${{ matrix.part }}
          path: output_${{ github.event.inputs.year }}_${{ matrix.month }}_part${{ matrix.part }}/*.json
