name: Bloomberg Harvester Matrix

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Année'
        required: true
        default: '2014'
      month:
        description: 'Mois (ex: 2)'
        required: true
        default: '2'
      test_mode:
        description: 'Mode Test (10 articles en 1 min) ?'
        type: boolean
        default: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        part: [1] # Pour le test rapide, 1 seul serveur suffit !
        month: [2]

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer Playwright & Firefox
        run: |
          npm install playwright
          npx playwright install --with-deps firefox

      - name: Lancer le test
        run: node harvest_chunk.js ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ matrix.part }} ${{ github.event.inputs.test_mode && 'TEST' || 'FULL' }}

      - name: Créer le fichier ZIP
        uses: actions/upload-artifact@v4
        with:
          name: test_articles_bloomberg
          path: output_${{ github.event.inputs.year }}_${{ github.event.inputs.month }}_part${{ matrix.part }}/*.json
